### PR TITLE
Added type annotations.

### PR DESCRIPTION
**Pull request by sdomoszlai13**
Added requested type annotations to adafruit_ms8607.py. Please take a look, @FoamyGuy .

### CODE REVIEW

**Comment by sdomoszlai13** [comment]
I have a problem with line 77. I need to add a tuple of objects of type Any, but can't make it work. The error now is:

File "/home/runner/work/Adafruit_CircuitPython_MS8607/Adafruit_CircuitPython_MS8607/adafruit_ms8607.py", line 77, in CV
    def add_values(cls, value_tuples: Tuple[Any, ...]) -> None:
                                            ^^^
NameError: name 'Any' is not defined

Error: Process completed with exit code 2.

Related question: pre-commit doesn't give me any error on my computer. I only encounter this error after pushing to GitHub. Is it possible to get the exact same error messages locally before pushing to GitHub? Maybe I'm doing something wrong.

**Comment by FoamyGuy** [comment]
My first guess for the error:
```
NameError: name 'Any' is not defined
```
Would be that `Any` was attempted to be used in a type annotation without having been imported first.

With regards to getting set up to see the same errors locally. The learn guide page here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code and the 2 pages that follow it cover the setup for `pre-commit`, `pylint`, and `black` which are the tools used for the actions checks that run automatically in github. 

Once you get them set up locally you can run them with a command like:
```
pre-commit run -a
```
and it will do all of the checks in your local instance and output any warnings or errors.

**Comment by sdomoszlai13** [comment]
Thanks for your quick reply @FoamyGuy !

Unfortunately, Any is imported and I still got the error.

Actually, I've been using pre-commit for a while and always check the files with it locally before committing. My problem is that the tests run without errors locally, so I commit, and then sometimes the 'GitHub version' of the tests throws errors, like the above one with the unknown Any NameError. I don't get this error when running pre-commit locally on my machine.

**Comment by sdomoszlai13** [comment]
I'm still having problems with plain module imports (ModuleNotFound errors). Currently, I get the following output:
[INFO] This may take a few minutes...
Error: black....................................................................Failed
- hook id: black
- files were modified by this hook

Error: reformatted adafruit_ms8607.py

All done! ✨ 🍰 ✨
1 file reformatted, 2 files left unchanged.

reuse....................................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
pylint (library code)....................................................Passed
pylint (example code)....................................................Passed
pylint (test code)...................................(no files to check)Skipped
Error: Process completed with exit code 1.

And also:
Run adafruit/circuitpython-action-library-ci-failed@v1
Error: Cannot read properties of undefined (reading 'number')

I really ran out of ideas. Can you help out @FoamyGuy ? Thanks!

**Comment by FoamyGuy** [comment]
Sorry for the delay, this one got lost for me. 

Unfortunately I don't really recognize the errors you posted:
```
Run adafruit/circuitpython-action-library-ci-failed@v1
Error: Cannot read properties of undefined (reading 'number')
```

The bit further up in the output about the Black formatting is expected output though. It means that Black did some reformatting and now the resulting changes need to be committed. 

I've run this locally now and will make a new commit with those changes.

**Review by FoamyGuy — APPROVED** [review]
The latest version looks good to me after the code formatting. 

Thanks for working on this @sdomoszlai13!

If you are still having issues when you run pre-commit locally you can try to get help on our discord as well.

**Pull request merged**
